### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by yahyalrq** [J22Melody/signwriting-translation#2]
Hello, I am writing a report on the different approaches to translating text to gloss. Could you please share more insights on what is your model? Which neural network it is using?

**Comment by bricksdont** [comment]
Hi,

Just to clarify: this repository is about translating from spoken language text to signwriting (or vice versa). Glosses are not involved.

The model that @J22Melody used is a sequence-to-sequence Transformer model (implemented either in joeynmt or Sockeye).

Does this answer your questions?

**Comment by bipinkrish** [comment]
> I am writing a report on the different approaches to translating text to gloss

have you done it?

**Comment by AmitMY** [comment]
Paper by @bricksdont https://aclanthology.org/2023.acl-short.60/
