### ISSUE TITLE
Can you share the trained model that you currently use for the API

### ISSUE THREAD

**Issue by bipinkrish** [J22Melody/signwriting-translation#4]

**Comment by J22Melody** [comment]
The models have been uploaded here:

https://drive.google.com/drive/folders/1u2uBm64vzfmccuPBoYJn54XadiOd6MP2?usp=sharing

Let me know whether it helps.

**Comment by bipinkrish** [comment]
> The models have been uploaded here:
> 
> [drive.google.com/drive/folders/1u2uBm64vzfmccuPBoYJn54XadiOd6MP2?usp=sharing](https://drive.google.com/drive/folders/1u2uBm64vzfmccuPBoYJn54XadiOd6MP2?usp=sharing)

Thank you.

I guess,

* `baseline_multilingual_plus` folder is for `SIGN to SPOKEN` ?

* This is not from `SignBank+` ?

I figure https://github.com/J22Melody/signwriting-translation/blob/main/app.py will help me load and use both the models ?

**Comment by J22Melody** [comment]
No, the models and the APIs are not from the latest SignBank+ work, but the [EACL 2023 work](https://aclanthology.org/2023.findings-eacl.127). We will publish SignBank+ and the new models soon (currently, it is a pre-print only). Thanks for your interest.

> baseline_multilingual_plus folder is for SIGN to SPOKEN

Correct. And the other one `sockeye_spoken2symbol_factor_0.1` is for SPOKEN to SIGN translation. We trained different models for different translation directions. Look at `app.py` and change the file paths to what you have downloaded should do the job.

**Comment by bipinkrish** [comment]
Ok, Thanks for the help.
