### ISSUE TITLE
How to use this project

### ISSUE THREAD

**Issue by DataScienceShow** [J22Melody/signwriting-translation#6]
HI there!
If I just clone this project,and run app.py file. Does it work? Or Should I install something else except required packages and modules.
When I run app.py file, it is returning error.
And I just want to use API for your already trained modules:
 
![photo_2024-05-05_18-27-34](https://github.com/J22Melody/signwriting-translation/assets/124051204/e91e803e-4849-4d5e-818b-bb35ec6ff617)

When I run app.py file according to above docs, it returns error:
![photo_2024-05-05_18-27-39](https://github.com/J22Melody/signwriting-translation/assets/124051204/d64b838f-0d57-4be9-9d7f-2bd71a3ba950)

**Comment by J22Melody** [comment]
Yes, it should work if you install the dependencies correctly. 

Could you check whether your `Sockeye` version is the same as written in the README?
